var swiper=new swiper(".popular-content",{
    slidesPerView:1,
    spaceBetween:10,
    autoplay:{
        delay:5500,
        disableOnInteraction:false,
    },
    pagination:{
        el:"swiper-pagination",
        clickable:true,
    },
    navigation:{
        nextE1:"swiper-button-next",
        prevE1:"swiper-button-prev",
    },
    breakpoints:{
        280:{
            slidesPerView:1,
            spaceBetween:10,
        },
        320:{
            slidesPerView:2,
            spaceBetween:10,
        },
        510:{
            slidesPerView:2,
            spaceBetween:10,
        },
        758:{
            slidesPerView:3,
            spaceBetween:15,
        },
        900:{
            slidesPerView:4,
            spaceBetween:20,
        },
    },
});